name: kof_hotel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blurrycontainer: 1.0.2
  icons_plus: ^4.0.0
  flutter_custom_clippers: ^2.1.0

  cupertino_icons: ^1.0.2

  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hotel/
    - assets/rooms/
    - assets/users/

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/font/Merienda-VariableFont_wght.ttf
